### ISSUE TITLE
Bad fastq file

### ISSUE THREAD

**Issue by jianshu93** [rcedgar/urmap#4]
00:00 84Mb 100% Reading index wp2740.bin.37.ufi 
00:05 6.2Gb 0.71% Mapping (paired) WP2740_1.fastq

urmap -map2 WP2740_1.fastq -reverse WP2740_2.fastq -ufi wp2740.bin.37.ufi -samout wp2740.bin.37.sam -threads 80
Elapsed time 00:05
Max memory 6.2Gb

---Fatal error---
Bad FASTQ record: 150 bases, 134 quals line 2831660 file WP2740_2.fastq label A00199:323:HJMY7DSXX:2:1107:9426:25113 2:N:0:AACCAGAG+TCTTTCCC

**Comment by rcedgar** [comment]
According to the error message, there is a bad FASTQ record where the number of bases (150) is different from the number of Q scores (134). So the default assumption is that you have a bad FASTQ file. If that FASTQ record is actually ok, then there is a bug. If the FASTQ files are small, I can take a look if you post them somewhere. If they are big, then please try to narrow down the problem by making smaller FASTQ files which reproduce the problem. You could do a binary search by splitting the files into two halves, seeing which half reproduces the problem and continuing with that half. Another approach is to use the fastx_subsample command in usearch to make a smaller subset. Using -threads > 1 may be a problem for reproducibility, if possible try to reproduce the problem with -threads 1.
